### ISSUE TITLE
Plugin crash on plan with data "confluent_environment"

### ISSUE THREAD

**Issue by rickard-von-essen** [confluentinc/terraform-provider-confluent#268]
When running `terraform plan -lock=false`, using

```
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/confluentinc/confluent v1.43.0
```

the plugin crashes with the following stacktrace:

```
[...]
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│
│   with module.confluent.data.confluent_environment.splat-prod-env,
│   on ../../modules/confluent/requirements.tf line 25, in data "confluent_environment" "splat-prod-env":
│   25: data "confluent_environment" "splat-prod-env" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-confluent_1.43.0 plugin:

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x279e0 pc=0x279e0]

runtime stack:
runtime.throw({0x13ff3d1?, 0x1?})
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/panic.go:1047 +0x5d fp=0x7f7b62ffbd68 sp=0x7f7b62ffbd38 pc=0x43809d
runtime.sigpanic()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/signal_unix.go:821 +0x3e9 fp=0x7f7b62ffbdc8 sp=0x7f7b62ffbd68 pc=0x44e5a9

goroutine 86 [syscall]:
runtime.cgocall(0xf388c0, 0xc0005b0558)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/cgocall.go:157 +0x5c fp=0xc0005b0530 sp=0xc0005b04f8 pc=0x406fdc
net._C2func_getaddrinfo(0xc000400330, 0x0, 0xc000353e60, 0xc0000146f0)
        /tmp/go-build2573432830/b099/_cgo_gotypes.go:99 +0x56 fp=0xc0005b0558 sp=0xc0005b0530 pc=0x628ed6
net._C_getaddrinfo.func1(0x410ac7?, 0x8?, 0x1203660?, 0xc000400301?)
        /home/semaphore/.goenv/versions/1.20.0/src/net/cgo_unix_cgo.go:74 +0x85 fp=0xc0005b05c0 sp=0xc0005b0558 pc=0x629aa5
net._C_getaddrinfo(0xc0005b0648?, 0xc8c9e7?, 0xc0000ba230?, 0xc000400108?)
        /home/semaphore/.goenv/versions/1.20.0/src/net/cgo_unix_cgo.go:74 +0x19 fp=0xc0005b05f0 sp=0xc0005b05c0 pc=0x6299d9
net.cgoLookupIPCNAME({0x13d2dc7, 0x3}, {0xc000400108, 0x13})
        /home/semaphore/.goenv/versions/1.20.0/src/net/cgo_unix.go:153 +0x175 fp=0xc0005b0738 sp=0xc0005b05f0 pc=0x5f65b5
net.cgoIPLookup(0x1d82b10?, {0x13d2dc7?, 0xc000400120?}, {0xc000400108?, 0xc0002fe630?})
        /home/semaphore/.goenv/versions/1.20.0/src/net/cgo_unix.go:210 +0x3b fp=0xc0005b07a8 sp=0xc0005b0738 pc=0x5f6c7b
net.cgoLookupIP.func1()
        /home/semaphore/.goenv/versions/1.20.0/src/net/cgo_unix.go:220 +0x36 fp=0xc0005b07e0 sp=0xc0005b07a8 pc=0x5f70b6
runtime.goexit()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005b07e8 sp=0xc0005b07e0 pc=0x46a961
created by net.cgoLookupIP
        /home/semaphore/.goenv/versions/1.20.0/src/net/cgo_unix.go:220 +0x12a

goroutine 1 [select]:
runtime.gopark(0xc00059f930?, 0x2?, 0x5?, 0x0?, 0xc00059f7b4?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:381 +0xd6 fp=0xc0005db540 sp=0xc0005db520 pc=0x43ae76
runtime.selectgo(0xc0005db930, 0xc00059f7b0, 0x1?, 0x0, 0xc00059f970?, 0x1)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/select.go:327 +0x7be fp=0xc0005db680 sp=0xc0005db540 pc=0x44a71e
github.com/hashicorp/go-plugin.Serve(0xc0000b0960)
        pkg/mod/github.com/hashicorp/go-plugin@v1.4.3/server.go:469 +0x14a5 fp=0xc0005dbb60 sp=0xc0005db680 pc=0xd3aac5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.Serve({0x13d7aa8, 0x8}, 0xc000136c80, {0x0, 0x0, 0x0})
        pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:311 +0xc0a fp=0xc0005dbda0 sp=0xc0005dbb60 pc=0xd52b2a
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.tf5serverServe(0xc0000b0240)
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/plugin/serve.go:178 +0x4d9 fp=0xc0005dbe80 sp=0xc0005dbda0 pc=0xd73e39
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve(0xc0000b0240)
        pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/plugin/serve.go:118 +0x18d fp=0xc0005dbf48 sp=0xc0005dbe80 pc=0xd737ed
main.main()
        src/github.com/confluentinc/terraform-provider-confluent/main.go:30 +0x6b fp=0xc0005dbf80 sp=0xc0005dbf48 pc=0xf387ab
runtime.main()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:250 +0x207 fp=0xc0005dbfe0 sp=0xc0005dbf80 pc=0x43aa47
runtime.goexit()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005dbfe8 sp=0xc0005dbfe0 pc=0x46a961

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:381 +0xd6 fp=0xc000086fb0 sp=0xc000086f90 pc=0x43ae76
runtime.goparkunlock(...)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:387
runtime.forcegchelper()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:305 +0xb0 fp=0xc000086fe0 sp=0xc000086fb0 pc=0x43acb0
runtime.goexit()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000086fe8 sp=0xc000086fe0 pc=0x46a961
created by runtime.init.6
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:381 +0xd6 fp=0xc000087780 sp=0xc000087760 pc=0x43ae76
runtime.goparkunlock(...)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000877c8 sp=0xc000087780 pc=0x42705e
runtime.gcenable.func1()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgc.go:178 +0x26 fp=0xc0000877e0 sp=0xc0000877c8 pc=0x41c2e6
runtime.goexit()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000877e8 sp=0xc0000877e0 pc=0x46a961
created by runtime.gcenable
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00004e070?, 0x1579880?, 0x0?, 0x0?, 0x0?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:381 +0xd6 fp=0xc000087f70 sp=0xc000087f50 pc=0x43ae76
runtime.goparkunlock(...)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x1d83720)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000087fa0 sp=0xc000087f70 pc=0x424f53
runtime.bgscavenge(0x0?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000087fc8 sp=0xc000087fa0 pc=0x425545
runtime.gcenable.func2()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgc.go:179 +0x26 fp=0xc000087fe0 sp=0xc000087fc8 pc=0x41c286
runtime.goexit()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000087fe8 sp=0xc000087fe0 pc=0x46a961
created by runtime.gcenable
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0x1441c50?, 0xa0?, 0xc0?, 0x1000000010?)
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/proc.go:381 +0xd6 fp=0xc000086628 sp=0xc000086608 pc=0x43ae76
runtime.runfinq()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mfinal.go:193 +0x107 fp=0xc0000867e0 sp=0xc000086628 pc=0x41b2a7
runtime.goexit()
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000867e8 sp=0xc0000867e0 pc=0x46a961
created by runtime.createfing
        /home/semaphore/.goenv/versions/1.20.0/src/runtime/mfinal.go:163 +0x45


Error: The terraform-provider-confluent_1.43.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by rickard-von-essen** [comment]
Duplicates #258
